### ISSUE TITLE
crash on Android when a Google Map is displayed

### ISSUE THREAD

**Issue by slicejunk** [rebeccahughes/react-native-device-info#105]
It crashes the app in the following configuration:
react-native: 0.35
react-native-device-info: 0.9.6
react-native-maps: 0.11.0
android : 6.0
google play services 9.8.77

here is the log:

```
10-19 02:55:20.525 15007 15028 V RenderScript: 0xdd34a000 Launching thread(s), CPUs 4
10-19 02:55:20.775 15007 15043 W unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.airbnb.android.react.maps.SizeReportingShadowNode
10-19 02:55:20.780 15007 15007 D AndroidRuntime: Shutting down VM
10-19 02:55:20.780 15007 15007 E AndroidRuntime: FATAL EXCEPTION: main
10-19 02:55:20.780 15007 15007 E AndroidRuntime: Process: com.myapp, PID: 15007
10-19 02:55:20.780 15007 15007 E AndroidRuntime: java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzab; or its super classes (declaration of 'com.google.android.gms.common.internal.zzab' appears in /data/app/com.myapp-1/base.apk)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at com.google.android.gms.maps.MapsInitializer.initialize(Unknown Source)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:66)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at com.airbnb.android.react.maps.AirMapManager.createViewInstance(AirMapManager.java:28)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at com.facebook.react.uimanager.ViewManager.createView(ViewManager.java:44)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at com.facebook.react.uimanager.NativeViewHierarchyManager.createView(NativeViewHierarchyManager.java:211)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at com.facebook.react.uimanager.UIViewOperationQueue$CreateViewOperation.execute(UIViewOperationQueue.java:148)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at com.facebook.react.uimanager.UIViewOperationQueue$2.run(UIViewOperationQueue.java:776)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at com.facebook.react.uimanager.UIViewOperationQueue.flushPendingBatches(UIViewOperationQueue.java:829)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at com.facebook.react.uimanager.UIViewOperationQueue.access$1500(UIViewOperationQueue.java:44)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at com.facebook.react.uimanager.UIViewOperationQueue$DispatchUIFrameCallback.doFrameGuarded(UIViewOperationQueue.java:868)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at com.facebook.react.uimanager.GuardedChoreographerFrameCallback.doFrame(GuardedChoreographerFrameCallback.java:32)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at com.facebook.react.uimanager.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:131)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:856)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at android.view.Choreographer.doCallbacks(Choreographer.java:670)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at android.view.Choreographer.doFrame(Choreographer.java:603)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at android.os.Handler.handleCallback(Handler.java:739)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:95)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:148)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5417)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Native Method)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-19 02:55:20.780 15007 15007 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-19 02:55:20.781   756  1134 W ActivityManager:   Force finishing activity com.myapp/.MainActivity
10-19 02:55:20.819   769   769 E EGL_emulation: tid 769: eglCreateSyncKHR(1215): error 0x3004 (EGL_BAD_ATTRIBUTE)
10-19 02:55:20.931   756  3912 I OpenGLRenderer: Initialized EGL, version 1.4
10-19 02:55:20.961   756  3912 W EGL_emulation: eglSurfaceAttrib not implemented
10-19 02:55:20.961   756  3912 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xdb367540, error=EGL_SUCCESS
10-19 02:55:21.403   756   776 W ActivityManager: Activity pause timeout for ActivityRecord{8020bfc u0 com.myapp/.MainActivity t233 f}
10-19 02:55:21.451  1149  1297 W EGL_emulation: eglSurfaceAttrib not implemented
10-19 02:55:21.452  1149  1297 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xdef9ca80, error=EGL_SUCCESS
10-19 02:55:21.814   756   776 I ActivityManager: Killing 14717:com.android.keychain/1000 (adj 15): empty #17
10-19 02:55:23.464 15007 15007 I Process : Sending signal. PID: 15007 SIG: 9
10-19 02:55:23.486   756  3912 E Surface : getSlotFromBufferLocked: unknown buffer: 0xdefc2230
10-19 02:55:23.489   756  3912 D OpenGLRenderer: endAllStagingAnimators on 0xdb3c8900 (RippleDrawable) with handle 0xdb364620
10-19 02:55:23.500   756  1808 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 104)
10-19 02:55:23.500   756  1808 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 15007 uid 10087
10-19 02:55:23.502   756  1808 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 104)
10-19 02:55:23.510   756   810 W InputDispatcher: channel '1c2bd71 com.myapp/com.myapp.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
10-19 02:55:23.510   756   810 E InputDispatcher: channel '1c2bd71 com.myapp/com.myapp.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
10-19 02:55:23.517   756   768 I ActivityManager: Process com.myapp (pid 15007) has died
10-19 02:55:23.517   756  2013 D GraphicsStats: Buffer count: 6
10-19 02:55:23.517   756  2603 I WindowState: WIN DEATH: Window{1c2bd71 u0 com.myapp/com.myapp.MainActivity}
10-19 02:55:23.517   756  2603 W InputDispatcher: Attempted to unregister already unregistered input channel '1c2bd71 com.myapp/com.myapp.MainActivity (server)'
10-19 02:55:23.663   756   787 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
```

**Comment by slicejunk** [comment]
this https://github.com/airbnb/react-native-maps/issues/669 fixes the issue

**Comment by petrovakd** [comment]
they fixed issue about incompatibility with fcm, but it does not help for device info library. still need help

**Comment by machour** [comment]
Documented how to disable com.google.android.gms in the [troubleshooting]( https://github.com/rebeccahughes/react-native-device-info#troubleshooting) section.
Will probably be dropped with next BC breaking release.
