### ISSUE TITLE
Crash on Android 7.0

### ISSUE THREAD

**Issue by syardumi** [rebeccahughes/react-native-device-info#184]
I'm getting a crash on initial load of the app. Here is the stacktrace:

06-19 16:20:06.136 30288-30349/com.cutanea.aktipak.facefwd.debug E/AndroidRuntime: FATAL EXCEPTION: mqt_js
Process: com.cutanea.aktipak.facefwd.debug, PID: 30288
java.lang.IllegalAccessError: Method 'void android.support.v4.content.ContextCompat.<init>()' is inaccessible to class 'com.google.android.gms.iid.zzd' (declaration of 'com.google.android.gms.iid.zzd' appears in /data/app/com.cutanea.aktipak.facefwd.debug-2/base.apk)
   at com.google.android.gms.iid.zzd.zzdo(Unknown Source)
   at com.google.android.gms.iid.zzd.<init>(Unknown Source)
   at com.google.android.gms.iid.zzd.<init>(Unknown Source)
   at com.google.android.gms.iid.InstanceID.zza(Unknown Source)
   at com.google.android.gms.iid.InstanceID.getInstance(Unknown Source)
   at com.learnium.RNDeviceInfo.RNDeviceModule.getConstants(RNDeviceModule.java:112)
   at com.facebook.react.cxxbridge.JavaModuleWrapper.getConstants(JavaModuleWrapper.java:102)
   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
   at android.os.Handler.handleCallback(Handler.java:751)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
   at android.os.Looper.loop(Looper.java:154)
   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
   at java.lang.Thread.run(Thread.java:761)

**Comment by bosung90** [comment]
react-native-device-info is installing com.google.android.gms:play-services-gcm that is incompatible with one or more of your libraries. I fixed it by forking this library and changing com.google.android.gms:play-services-gcm:+ to com.google.android.gms:play-services-gcm:10.2.4 (which was required by react-native-maps in my case)

**Comment by machour** [comment]
Documented in the [troubleshooting](https://github.com/rebeccahughes/react-native-device-info#troubleshooting) section

**Comment by montaserfzy** [comment]
in `android/app/build.gradle`

replace  `compile(project(':react-native-device-info'))` with 
`compile(project(':react-native-device-info')) {
     exclude group: 'com.google.android.gms'
}`

**Comment by mikehardy** [comment]
@montaserfzy that's not great advice. You only need to do that if you have not correctly specified your play services library version in the ext block. [Follow the example](https://github.com/react-native-community/react-native-device-info/blob/master/example/android/build.gradle#L4)
