### ISSUE TITLE
Native module RNDeviceModule tried to override RNDeviceModule for module name RNDeviceInfo

### ISSUE THREAD

**Issue by sibelius** [rebeccahughes/react-native-device-info#243]
I've got this error on Fabric Crashlytics
android 6

using the latest version of this package

```jsx
Fatal Exception: java.lang.IllegalStateException: Native module RNDeviceModule tried to override RNDeviceModule for module name RNDeviceInfo. If this was your intention, set canOverrideExistingModule=true
       at com.facebook.react.NativeModuleRegistryBuilder.addNativeModule(NativeModuleRegistryBuilder.java:121)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:109)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1050)
       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1021)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:959)
       at com.facebook.react.ReactInstanceManager.access$600(ReactInstanceManager.java:109)
       at com.facebook.react.ReactInstanceManager$4.run(ReactInstanceManager.java:802)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by vonovak** [comment]
check your `MainApplication.java`, in particular `protected List<ReactPackage> getPackages()`; the `RNDeviceModule` is probably twice in the list

**Comment by kyungjoongo** [comment]
great!

**Comment by jakeOliv** [comment]
Thanks buddy

**Comment by fajartc02** [comment]
Great I have same problem, finally solved .. Thank You
