### ISSUE TITLE
Crash on calling `getConstants()`

### ISSUE THREAD

**Issue by itchingpixels** [rebeccahughes/react-native-device-info#277]
Hi,

Thanks for this lib! We've been finding it super useful.

Today, we noticed that this crash seems to be happening quite frequently :

```Fatal Exception: com.facebook.react.common.JavascriptException: Java exception in 'NativeModules'

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.app.Activity.checkCallingOrSelfPermission(java.lang.String)' on a null object reference, stack:
com.learnium.RNDeviceInfo.RNDeviceModule.getConstants@136
com.facebook.react.bridge.JavaModuleWrapper.getConstants@140
android.os.Handler.handleCallback@743
android.os.Handler.dispatchMessage@95
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage@31
<unknown>@462:48
t@2:633
<unknown>@2:224
e@2:231
<unknown>@461:220
t@2:633
<unknown>@2:224
e@2:231
<unknown>@457:387
t@2:633
<unknown>@2:224
e@2:231
<unknown>@454:111
t@2:633
<unknown>@2:224
e@2:231
<unknown>@452:233
t@2:633
<unknown>@2:224
e@2:231
<unknown>@339:218
t@2:633
<unknown>@2:224
e@2:231
<unknown>@338:79
t@2:633
<unknown>@2:224
e@2:231
<unknown>@337:145
t@2:633
<unknown>@2:224
e@2:231
<unknown>@299:145
t@2:633
<unknown>@2:224
e@2:231
<unknown>@12:38
t@2:633
<unknown>@2:154
e@2:231
global code@1163:9

       at com.facebook.react.modules.core.ExceptionsManagerModule.showOrThrowError(ExceptionsManagerModule.java:56)
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportFatalException(ExceptionsManagerModule.java:40)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:743)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
       at android.os.Looper.loop(Looper.java:150)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
       at java.lang.Thread.run(Thread.java:833)```

Do you have any advice on how to resolve this?

Thank you!

**Comment by itchingpixels** [comment]
As far as I can see, this is fixed in the latest version. We'll try to upgrade and close this issue in the meantime.
