### ISSUE TITLE
Multiple dex files define Lcom/google/android/gms/internal/zzfgn

### ISSUE THREAD

**Issue by leobetosouza** [rebeccahughes/react-native-device-info#348]
## Summary

|             |     |
| ----------- | --- |
| Version     | 0.17.3  |
| Affected OS | Android  |
| OS Version  | 23   |

## Current behavior

When a try to build app with `react-native-device-info` I'm getting this error:

```Running dex in-process requires build tools 23.0.2.
For faster builds update this project to use the latest build tools.
Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzfgn;
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzfgn;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

:app:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED```

Modules on my `package.json`:

```  "dependencies": {
    "prop-types": "^15.6.0",
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-native-add-calendar-event": "^0.3.0",
    "react-native-config": "^0.11.5",
    "react-native-device-info": "^0.17.3",
    "react-native-firebase": "^3.2.4",
    "react-native-geocoder": "^0.5.0",
    "react-native-htmlview": "^0.12.1",
    "react-native-render-html": "^3.7.0",
    "react-native-root-toast": "^3.0.0",
    "react-native-searchbar": "^1.14.0",
    "react-native-swipeout": "^2.3.3",
    "react-native-vector-icons": "^4.5.0",
    "react-navigation": "^1.0.0-beta.26",
    "redux-zero": "^4.10.0"
  },```

## Expected behavior

No errors

**Comment by machour** [comment]
This is covered in the troubleshooting section and will be removed in next BC breaking release. 
   https://github.com/rebeccahughes/react-native-device-info#troubleshooting
