### ISSUE TITLE
Naming collision when React Cocoapod is added

### ISSUE THREAD

**Issue by joanbarros** [rebeccahughes/react-native-device-info#38]
I'm currently having an issue where the same file is being added two times to the project (Xcode).

The issue is with the `polyfills.js` file but it is adding React again. All the files added are already in the project added by `npm`.

```
⋊> ~/D/P/QueueProject on master ⨯ react-native start                              21:25:13
 ┌────────────────────────────────────────────────────────────────────────────┐
 │  Running packager on port 8081.                                            │
 │                                                                            │
 │  Keep this packager running while developing on any JS projects. Feel      │
 │  free to close this tab and run your own packager instance if you          │
 │  prefer.                                                                   │
 │                                                                            │
 │  https://github.com/facebook/react-native                                  │
 │                                                                            │
 └────────────────────────────────────────────────────────────────────────────┘
Looking for JS files in
   /Users/joanbarros/Development/Projects/QueueProject

[10:21:11 PM] <START> Building Dependency Graph
[10:21:11 PM] <START> Crawling File System
[Hot Module Replacement] Server listening on /hot

React packager ready.

[10:21:12 PM] <END>   Crawling File System (1152ms)
[10:21:12 PM] <START> Building in-memory fs for JavaScript
[10:21:12 PM] <END>   Building in-memory fs for JavaScript (640ms)
[10:21:12 PM] <START> Building in-memory fs for Assets
[10:21:13 PM] <END>   Building in-memory fs for Assets (365ms)
[10:21:13 PM] <START> Building Haste Map
[10:21:13 PM] <START> Building (deprecated) Asset Map
[10:21:13 PM] <END>   Building (deprecated) Asset Map (68ms)
Failed to build DependencyGraph: Naming collision detected: /Users/joanbarros/Development/Projects/QueueProject/ios/Pods/React/packager/react-packager/src/DependencyResolver/polyfills/polyfills.js collides with /Users/joanbarros/Development/Projects/QueueProject/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/polyfills.js
Error: Naming collision detected: /Users/joanbarros/Development/Projects/QueueProject/ios/Pods/React/packager/react-packager/src/DependencyResolver/polyfills/polyfills.js collides with /Users/joanbarros/Development/Projects/QueueProject/node_modules/react-native/packager/react-packager/src/Resolver/polyfills/polyfills.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/Users/joanbarros/Development/Projects/QueueProject/node_modules/promise/lib/core.js:37:12)
    at /Users/joanbarros/Development/Projects/QueueProject/node_modules/promise/lib/core.js:123:15
    at flush (/Users/joanbarros/Development/Projects/QueueProject/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

**Comment by whitmanc** [comment]
Same problem here using pods installation method.

**Comment by johncblandii** [comment]
Any fix for this? It is killing my productivity trying to upgrade to RN 0.40. 

I have an `rn-cli.config.js` with the following:
```
var blacklist = require('react-native/packager/blacklist');

var config = {
  getBlacklistRE() {
    var bl = blacklist([
      /Pods[\/\\]React[\/\\].*/
    ]);
    console.log(bl);
    return bl;
  }
};

module.exports = config;
```

That `console.log` spits out the following regex for blacklisting and is clearly ignoring my instructions:
```
/(Pods[\/\\]React[\/\\].*|node_modules[\/\\]react[\/\\]dist[\/\\].*|website\/node_modules\/.*|Libraries\/Relay\/relay\/tools\/relayUnstableBatchedUpdates\.js|heapCapture\/bundle\.js)$/
```

I've also tried:
```
/(Pods\/React\/.*|node_modules[\/\\]react[\/\\]dist[\/\\].*|website\/node_modules\/.*|Libraries\/Relay\/relay\/tools\/relayUnstableBatchedUpdates\.js|heapCapture\/bundle\.js)$/
```

...and...
```
/(Pods\/.*|node_modules[\/\\]react[\/\\]dist[\/\\].*|website\/node_modules\/.*|Libraries\/Relay\/relay\/tools\/relayUnstableBatchedUpdates\.js|heapCapture\/bundle\.js)$/
```

...all to no avail. I continue to get this error or something similar:
```
React packager ready.

[01/26/2017, 01:48:18] <START> Building Haste Map
Failed to build DependencyGraph: @providesModule naming collision:
  Duplicate module name: react-native-packager
  Paths: /Users/johncblandii/Work/hubhuman/mobile-platform/app/Pods/React/packager/package.json collides with /Users/johncblandii/Work/hubhuman/mobile-platform/app/node_modules/react-native/packager/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
Error: @providesModule naming collision:
  Duplicate module name: react-native-packager
  Paths: /Users/johncblandii/Work/hubhuman/mobile-platform/app/Pods/React/packager/package.json collides with /Users/johncblandii/Work/hubhuman/mobile-platform/app/node_modules/react-native/packager/package.json

This error is caused by a @providesModule declaration with the same name across two different files.
    at HasteMap._updateHasteMap (/Users/johncblandii/Work/hubhuman/mobile-platform/app/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:158:13)
    at p.getName.then.name (/Users/johncblandii/Work/hubhuman/mobile-platform/app/node_modules/react-native/packager/react-packager/src/node-haste/DependencyGraph/HasteMap.js:133:31)
```

**Comment by machour** [comment]
@johncblandii we had a similar issue on gitpoint and ended up coming up with this solution: https://github.com/gitpoint/git-point/blob/master/rn-cli.config.js

**Comment by machour** [comment]
@joanbarros is this still happening for you?

**Comment by machour** [comment]
Sorry, I meant to close #39 -_-

**Comment by machour** [comment]
Closing this as no feedback was provided.
